# Generated by Django 4.2.2 on 2023-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tusks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('tusk_description', models.TextField(max_length=1500, verbose_name='Описание задачи')),
                ('date', models.DateTimeField(verbose_name='Дедлайн задачи')),
            ],
        ),
    ]
